Asg2/mysite/figma/urls.py
from django.urls import path

from . import views

app_name = 'figma' # name spacing the URL's
urlpatterns = [
    path('', views.home, name='home'),
]

Asg2/mysite/polls/urls.py
""" from django.urls import path

from . import views

app_name = 'polls' # name spacing the URL's
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
] """

### GENERIC VIEWS
from django.urls import path

from . import views

app_name = 'polls' # name spacing the URL's
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Asg2/mysite/figma/models.py
from django.db import models

# Create your models here.

Asg2/mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=500)
    published_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='published_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.published_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=250)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

Asg2/mysite/figma/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'figma/home.html')

Asg2/mysite/polls/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html' # use our existing "polls/index.html" template.
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        # return Question.objects.order_by('-pubpublished_date')[:5] #bug

        # returns a queryset containing Questions whose pub_date is less than or equal to - that is, earlier than or equal to - timezone.now.
        return Question.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:5] 


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html' # uses the template "polls/question_detail.html"
    
    def get_queryset(self):
        return Question.objects.filter(published_date__lte=timezone.now()) # lte = less than or equal to


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    def get_queryset(self):
        return Question.objects.filter(published_date__lte=timezone.now()) # lte = less than or equal to


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


""" def index(request):
    latest_question_list = Question.objects.order_by('-published_date')[:5]
    context = {'latest_question_list': latest_question_list,}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice']) 
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id))) """

Asg2/mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %} <!-- Cross Site Request Forgeries -->
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

Asg2/mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<h1> Welcome to Polls index Page</h1>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li> <!--name spaced representations-->
        <li><a href="{% url 'figma:home' %}">Go Back to Home Page</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

Asg2/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>